#Web服务器：apache | nginx，通过交互式选择获取
zentao_webs: apache

zentao_vhost_dir: /etc/httpd/vhost
zentao_vhost_src: vhost.conf
zentao_service: httpd
zentao_db_password: "123456"
zentao_owner: apache
zentao_name: "zentao"
zentao_title: "Zentao"

#发行版：zh | int
zentao_distribution: "zh"
#下载链接需定期维护
zentao_download_url_meta: 
  "zh": 
    "url": "https://www.zentao.net/dl/ZenTaoPMS.12.4.1.zip"  
    
  "int": 
    "url": "https://www.zentao.net/dl/ZenTaoALM.12.4.1.int.zip"
